import * as Localization from "expo-localization";

const locale = Localization.getLocales()[0];
const langCode = locale ? locale.languageCode : "en";

const ALL_TEXTS: { [key: string]: { [key: string]: string } } = {
  en: {
    // English
    scanQR: "Scan QR",
    manualEntry: "Manual Entry",
    unknownIssuer: "Unknown",
    addAccount: "Add Account",
    cancel: "Cancel",
    myKeys: "My keys",
    empty: "No accounts yet.",
    emptySub: "Tap + to add one.",
    delete: "Delete",
    confirmDelete: "Are you sure you want to delete",
    confirmDelete2: "account(s)?",
    options: "Account Options",
    newAccount: "New Account",
    accNameLabel: "Account Name *",
    accNamePlace: "Ex: My Personal Email",
    issuerLabel: "Provider (Optional)",
    issuerPlace: "Ex: Google, Amazon...",
    secretLabel: "Secret Key *",
    secretPlace: "JBSWY3DP...",
    iconLabel: "Icon",
    colorLabel: "Label Color",
    save: "Save Account",
    saving: "Saving...",
    errorTitle: "Error",
    errorMissing: "Please enter at least a name and a secret key.",
    errorShort: "Secret key seems too short.",
    errorSave: "Could not save account.",
    selected: "Selected",
    move: "Move",
    folder: "Folder",
    newFolder: "New Folder",
    folderNameLabel: "Folder Name *",
    folderIconLabel: "Icon",
    folderColorLabel: "Color",
  },
  es: {
    // Spanish
    scanQR: "Escanear QR",
    manualEntry: "Entrada Manual",
    unknownIssuer: "Desconocido",
    addAccount: "Añadir Cuenta",
    cancel: "Cancelar",
    myKeys: "Mis claves",
    empty: "No tienes cuentas aún.",
    emptySub: "Pulsa el + para añadir una.",
    delete: "Eliminar",
    confirmDelete: "¿Estás seguro de eliminar",
    confirmDelete2: "elemento(s) seleccionados?",
    options: "Opciones de cuenta",
    newAccount: "Nueva Cuenta",
    accNameLabel: "Nombre de la cuenta *",
    accNamePlace: "Ej: Mi Correo Personal",
    issuerLabel: "Proveedor (Opcional)",
    issuerPlace: "Ej: google, amazon...",
    secretLabel: "Clave Secreta (Key) *",
    iconLabel: "Icono",
    secretPlace: "JBSWY3DP...",
    colorLabel: "Color de etiqueta",
    save: "Guardar Cuenta",
    saving: "Guardando...",
    errorTitle: "Faltan datos",
    errorMissing: "Por favor, introduce al menos un nombre y la clave secreta.",
    errorShort: "La clave secreta parece demasiado corta.",
    errorSave: "No se pudo guardar la cuenta.",
    selected: "Seleccionado(s)",
    move: "Mover",
    folder: "Carpeta",
    newFolder: "Nueva Carpeta",
    folderNameLabel: "Nombre de la Carpeta *",
    folderIconLabel: "Icono",
    folderColorLabel: "Color",
  },
  fr: {
    // French
    scanQR: "Scanner QR",
    manualEntry: "Saisie Manuelle",
    unknownIssuer: "Inconnu",
    addAccount: "Ajouter un compte",
    cancel: "Annuler",
    myKeys: "Mes Clés",
    empty: "Pas encore de comptes.",
    emptySub: "Appuyez sur + pour ajouter.",
    delete: "Supprimer",
    confirmDelete: "Que voulez-vous faire avec",
    options: "Options du compte",
    newAccount: "Nueva Cuenta",
    accNameLabel: "Nombre de la cuenta *",
    accNamePlace: "Ej: Mi Correo Personal",
    issuerLabel: "Proveedor (Opcional)",
    issuerPlace: "Ej: google, amazon...",
    secretLabel: "Clave Secreta (Key) *",
    secretPlace: "JBSWY3DP...",
    colorLabel: "Color de etiqueta",
    save: "Guardar Cuenta",
    saving: "Guardando...",
    errorTitle: "Faltan datos",
    errorMissing: "Por favor, introduce al menos un nombre y la clave secreta.",
    errorShort: "La clave secreta parece demasiado corta.",
    errorSave: "No se pudo guardar la cuenta.",
  },
  de: {
    // German
    scanQR: "QR scannen",
    manualEntry: "Manuelle Eingabe",
    unknownIssuer: "Unbekannt",
    addAccount: "Konto hinzufügen",
    cancel: "Abbrechen",
    myKeys: "Meine Schlüssel",
    empty: "Noch keine Konten.",
    emptySub: "Tippen Sie auf +, um eins hinzuzufügen.",
    delete: "Löschen",
    confirmDelete: "Was möchten Sie tun mit",
    options: "Kontooptionen",
    newAccount: "Nueva Cuenta",
    accNameLabel: "Nombre de la cuenta *",
    accNamePlace: "Ej: Mi Correo Personal",
    issuerLabel: "Proveedor (Opcional)",
    issuerPlace: "Ej: google, amazon...",
    secretLabel: "Clave Secreta (Key) *",
    secretPlace: "JBSWY3DP...",
    colorLabel: "Color de etiqueta",
    save: "Guardar Cuenta",
    saving: "Guardando...",
    errorTitle: "Faltan datos",
    errorMissing: "Por favor, introduce al menos un nombre y la clave secreta.",
    errorShort: "La clave secreta parece demasiado corta.",
    errorSave: "No se pudo guardar la cuenta.",
  },
  it: {
    // Italian
    scanQR: "Scansiona QR",
    manualEntry: "Inserimento Manuale",
    unknownIssuer: "Sconosciuto",
    addAccount: "Aggiungi Account",
    cancel: "Annulla",
    myKeys: "Le mie chiavi",
    empty: "Nessun account ancora.",
    emptySub: "Tocca + per aggiungerne uno.",
    delete: "Elimina",
    confirmDelete: "Cosa vuoi fare con",
    options: "Opzioni account",
    newAccount: "Nueva Cuenta",
    accNameLabel: "Nombre de la cuenta *",
    accNamePlace: "Ej: Mi Correo Personal",
    issuerLabel: "Proveedor (Opcional)",
    issuerPlace: "Ej: google, amazon...",
    secretLabel: "Clave Secreta (Key) *",
    secretPlace: "JBSWY3DP...",
    colorLabel: "Color de etiqueta",
    save: "Guardar Cuenta",
    saving: "Guardando...",
    errorTitle: "Faltan datos",
    errorMissing: "Por favor, introduce al menos un nombre y la clave secreta.",
    errorShort: "La clave secreta parece demasiado corta.",
    errorSave: "No se pudo guardar la cuenta.",
  },
};

export const TEXTS = ALL_TEXTS[langCode || "en"];
