import * as Localization from "expo-localization";
import { APP_NAME } from "./AppInformation";

const locale = Localization.getLocales()[0];
const langCode = locale ? locale.languageCode : "en";

const ALL_TEXTS: { [key: string]: { [key: string]: string } } = {
  en: {
    // English
    invalidCode: "Invalid code",
    invalidCodeMsg:
      "The scanned QR code does not appear to be a valid authentication code.",
    ok: "OK",
    grantPermission: "Grant Permission",
    cameraAccessMsg: "We need camera access to scan the QR code.",
    scanQR: "Scan QR",
    scanQR2: "Scan the QR code",
    manualEntry: "Manual Entry",
    unknownIssuer: "Unknown",
    addAccount: "Add Account",
    cancel: "Cancel",
    myKeys: "My keys",
    empty: "No accounts yet.",
    emptySub: "Tap + to add one.",
    delete: "Delete",
    deleteItems: "Delete items?",
    deleteAccounts: "Delete accounts?",
    deleteDefinitely: "Delete definitely",
    confirmDelete: "You are about to delete",
    confirmDelete2: "item(s)",
    confirmDelete3:
      "\nIf you delete a folder, everything inside will also be deleted.\nThis action cannot be undone.",
    options: "Account Options",
    newAccount: "New Account",
    accNameLabel: "Account Name *",
    accNamePlace: "Ex: My Personal Email",
    issuerLabel: "Provider (Optional)",
    issuerPlace: "Ex: Google, Amazon...",
    secretLabel: "Secret Key *",
    secretPlace: "JBSWY3DP...",
    iconLabel: "Icon",
    colorLabel: "Label Color",
    save: "Save Account",
    saving: "Saving...",
    errorTitle: "Error",
    errorMissing: "Please enter at least a name and a secret key.",
    errorShort: "Secret key seems too short.",
    errorSave: "Could not save account.",
    selectedOneItem: "Selected",
    selectedMoreItems: "Selected",
    move: "Move",
    moveAccounts: "Move accounts",
    folder: "Folder",
    newFolder: "New Folder",
    createFolder: "Create Folder",
    folderNameLabel: "Folder Name *",
    folderIconLabel: "Icon",
    folderColorLabel: "Color",
    principalFolder: "No folder",
    noFoldersCreated: "You have no folders created. Please create one first.",
    emptyFolder: "This folder is empty.",
    errorMissingName: "Folder name is required.",
    pressToStart: "Tap + to get started",
    settings: "Settings",
    security: "Security",
    biometricBlockTitle: "Biometric Authentication",
    biometricBlockSubtitle: "FaceID / Fingerprint",
    keysManagement: "Keys Management",
    exportKeys: "Export Keys",
    importKeys: "Import Keys",
    app: "App",
    privacyPolicy: "Privacy Policy",
    about: "About",
    appDescription:
      "A secure, private, and open-source two-factor authenticator (2FA). Your keys never leave your device.",
    seeGitHub: "See code on GitHub",
    technologiesAndCredits: "Technologies & Credits",
    frameworkCore: "Framework Code",
    ecosystem: "Ecosystem",
    navigation: "Navigation",
    iconography: "Iconography",
    secureStorage: "Secure Storage",
    createdWithLove: "Created with love for Free Software",
    gotIt: "Got it",
    unlockApp: `Unlock ${APP_NAME}`,
    usePin: "Use PIN",
    verifyIdentity: "Verify your identity to access.",
    verifyIdentityFallback: "Enter your PIN to access.",
    unlock: "Unlock",
    appBlocked: `${APP_NAME} is locked`,
    none: "None",
    folderNamePlace: "Ex: Work, Personal...",
    selectDestination: "Select destination for",
    selectDestination2: "account(s)",
  },
  es: {
    // Spanish
    invalidCode: "Código no válido",
    invalidCodeMsg:
      "El código QR escaneado no parece ser un código de autenticación válido.",
    ok: "OK",
    grantPermission: "Conceder Permiso",
    cameraAccessMsg:
      "Necesitamos acceso a la cámara para escanear el código QR.",
    scanQR: "Escanear QR",
    scanQR2: "Escanear el código QR",
    manualEntry: "Entrada Manual",
    unknownIssuer: "Desconocido",
    addAccount: "Añadir Cuenta",
    cancel: "Cancelar",
    myKeys: "Mis claves",
    empty: "No tienes cuentas aún.",
    emptySub: "Pulsa el + para añadir una.",
    delete: "Eliminar",
    deleteItems: "¿Eliminar elementos?",
    deleteAccounts: "¿Eliminar cuentas?",
    deleteDefinitely: "Eliminar definitivamente",
    confirmDelete: "Estás a punto de eliminar",
    confirmDelete2: "elemento(s)",
    confirmDelete3:
      "\nSi eliminas una carpeta, también se borrará lo que haya dentro.\nEsta acción no se puede deshacer.",
    options: "Opciones de cuenta",
    newAccount: "Nueva Cuenta",
    accNameLabel: "Nombre de la cuenta *",
    accNamePlace: "Ej: Mi Correo Personal",
    issuerLabel: "Proveedor (Opcional)",
    issuerPlace: "Ej: google, amazon...",
    secretLabel: "Clave Secreta (Key) *",
    secretPlace: "JBSWY3DP...",
    iconLabel: "Icono",
    colorLabel: "Color de etiqueta",
    save: "Guardar Cuenta",
    saving: "Guardando...",
    errorTitle: "Faltan datos",
    errorMissing: "Por favor, introduce al menos un nombre y la clave secreta.",
    errorShort: "La clave secreta parece demasiado corta.",
    errorSave: "No se pudo guardar la cuenta.",
    selectedOneItem: "Seleccionado",
    selectedMoreItems: "Seleccionados",
    move: "Mover",
    moveAccounts: "Mover cuentas",
    folder: "Carpeta",
    newFolder: "Nueva Carpeta",
    createFolder: "Crear Carpeta",
    folderNameLabel: "Nombre de la Carpeta *",
    folderIconLabel: "Icono",
    folderColorLabel: "Color",
    principalFolder: "Sin carpeta",
    noFoldersCreated: "No tienes carpetas creadas. Crea una primero.",
    emptyFolder: "Esta carpeta está vacía.",
    errorMissingName: "El nombre de la carpeta es obligatorio.",
    pressToStart: "Pulsa + para empezar",
    settings: "Ajustes",
    security: "Seguridad",
    biometricBlockTitle: "Autenticación Biométrica",
    biometricBlockSubtitle: "FaceID / Huella dactilar",
    keysManagement: "Gestión de claves",
    exportKeys: "Exportar claves",
    importKeys: "Importar claves",
    app: "Aplicación",
    privacyPolicy: "Política de Privacidad",
    about: "Acerca de",
    appDescription:
      "Un autenticador de doble factor (2FA) seguro, privado y de código abierto. Tus claves nunca salen de tu dispositivo.",
    seeGitHub: "Ver código en GitHub",
    technologiesAndCredits: "Tecnologías y Créditos",
    frameworkCore: "Código del Framework",
    ecosystem: "Ecosistema",
    navigation: "Navegación",
    iconography: "Iconografía",
    secureStorage: "Almacenamiento Seguro",
    createdWithLove: "Creado con amor por el Software Libre",
    gotIt: "Entendido",
    unlockApp: `Desbloquear ${APP_NAME}`,
    usePin: "Usar PIN",
    verifyIdentity: "Verifica tu identidad para acceder.",
    verifyIdentityFallback: "Introduce tu PIN para acceder.",
    unlock: "Desbloquear",
    appBlocked: `${APP_NAME} está bloqueada`,
    none: "Ninguna",
    folderNamePlace: "Ej: Trabajo, Personal...",
    selectDestination: "Selecciona el destino para",
    selectDestination2: "cuenta(s)",
  },
  fr: {
    // French
    invalidCode: "Code invalide",
    invalidCodeMsg:
      "Le code QR scanné ne semble pas être un code d'authentification valide.",
    ok: "OK",
    grantPermission: "Autoriser",
    cameraAccessMsg:
      "Nous avons besoin d'accéder à la caméra pour scanner le code QR.",
    scanQR: "Scanner QR",
    scanQR2: "Scanner le code QR",
    manualEntry: "Saisie manuelle",
    unknownIssuer: "Inconnu",
    addAccount: "Ajouter un compte",
    cancel: "Annuler",
    myKeys: "Mes clés",
    empty: "Pas encore de comptes.",
    emptySub: "Appuyez sur + pour en ajouter un.",
    delete: "Supprimer",
    deleteItems: "Supprimer les éléments ?",
    deleteAccounts: "Supprimer les comptes ?",
    deleteDefinitely: "Supprimer définitivement",
    confirmDelete: "Vous êtes sur le point de supprimer",
    confirmDelete2: "élément(s)",
    confirmDelete3:
      "\nSi vous supprimez un dossier, tout ce qu'il contient sera également supprimé.\nCette action est irréversible.",
    options: "Options du compte",
    newAccount: "Nouveau compte",
    accNameLabel: "Nom du compte *",
    accNamePlace: "Ex : Mon e-mail personnel",
    issuerLabel: "Fournisseur (Facultatif)",
    issuerPlace: "Ex : Google, Amazon...",
    secretLabel: "Clé secrète (Key) *",
    secretPlace: "JBSWY3DP...",
    iconLabel: "Icône",
    colorLabel: "Couleur de l'étiquette",
    save: "Enregistrer le compte",
    saving: "Enregistrement...",
    errorTitle: "Erreur",
    errorMissing: "Veuillez saisir au moins un nom et une clé secrète.",
    errorShort: "La clé secrète semble trop courte.",
    errorSave: "Impossible d'enregistrer le compte.",
    selectedOneItem: "Sélectionné",
    selectedMoreItems: "Sélectionnés",
    move: "Déplacer",
    moveAccounts: "Déplacer les comptes",
    folder: "Dossier",
    newFolder: "Nouveau dossier",
    createFolder: "Créer un dossier",
    folderNameLabel: "Nom du dossier *",
    folderIconLabel: "Icône",
    folderColorLabel: "Couleur",
    principalFolder: "Aucun dossier",
    noFoldersCreated:
      "Vous n'avez créé aucun dossier. Veuillez en créer un d'abord.",
    emptyFolder: "Ce dossier est vide.",
    errorMissingName: "Le nom du dossier est requis.",
    pressToStart: "Appuyez sur + pour commencer",
    settings: "Paramètres",
    security: "Sécurité",
    biometricBlockTitle: "Authentification biométrique",
    biometricBlockSubtitle: "FaceID / Empreinte digitale",
    keysManagement: "Gestion des clés",
    exportKeys: "Exporter les clés",
    importKeys: "Importer des clés",
    app: "Application",
    privacyPolicy: "Politique de confidentialité",
    about: "À propos",
    appDescription:
      "Un authentificateur à deux facteurs (2FA) sécurisé, privé et open source. Vos clés ne quittent jamais votre appareil.",
    seeGitHub: "Voir le code sur GitHub",
    technologiesAndCredits: "Technologies et crédits",
    frameworkCore: "Code du Framework",
    ecosystem: "Écosystème",
    navigation: "Navigation",
    iconography: "Iconographie",
    secureStorage: "Stockage sécurisé",
    createdWithLove: "Créé avec amour pour le Logiciel Libre",
    gotIt: "Compris",
    unlockApp: `Déverrouiller ${APP_NAME}`,
    usePin: "Utiliser le code PIN",
    verifyIdentity: "Vérifiez votre identité pour accéder.",
    verifyIdentityFallback: "Entrez votre code PIN pour accéder.",
    unlock: "Déverrouiller",
    appBlocked: `${APP_NAME} est verrouillée`,
    none: "Aucun",
    folderNamePlace: "Ex : Travail, Personnel...",
    selectDestination: "Sélectionnez la destination pour",
    selectDestination2: "compte(s)",
  },
  de: {
    // German
    invalidCode: "Ungültiger Code",
    invalidCodeMsg:
      "Der gescannte QR-Code scheint kein gültiger Authentifizierungscode zu sein.",
    ok: "OK",
    grantPermission: "Erlaubnis erteilen",
    cameraAccessMsg:
      "Wir benötigen Zugriff auf die Kamera, um den QR-Code zu scannen.",
    scanQR: "QR scannen",
    scanQR2: "Den QR-Code scannen",
    manualEntry: "Manuelle Eingabe",
    unknownIssuer: "Unbekannt",
    addAccount: "Konto hinzufügen",
    cancel: "Abbrechen",
    myKeys: "Meine Schlüssel",
    empty: "Noch keine Konten.",
    emptySub: "Tippen Sie auf +, um eins hinzuzufügen.",
    delete: "Löschen",
    deleteItems: "Elemente löschen?",
    deleteAccounts: "Konten löschen?",
    deleteDefinitely: "Endgültig löschen",
    confirmDelete: "Sie sind dabei, Folgendes zu löschen:",
    confirmDelete2: "Element(e)",
    confirmDelete3:
      "\nWenn Sie einen Ordner löschen, wird auch der gesamte Inhalt gelöscht.\nDiese Aktion kann nicht rückgängig gemacht werden.",
    options: "Kontooptionen",
    newAccount: "Neues Konto",
    accNameLabel: "Kontoname *",
    accNamePlace: "Bsp.: Meine private E-Mail",
    issuerLabel: "Anbieter (Optional)",
    issuerPlace: "Bsp.: Google, Amazon...",
    secretLabel: "Geheimer Schlüssel (Key) *",
    secretPlace: "JBSWY3DP...",
    iconLabel: "Icon",
    colorLabel: "Etikettenfarbe",
    save: "Konto speichern",
    saving: "Speichern...",
    errorTitle: "Fehler",
    errorMissing:
      "Bitte geben Sie mindestens einen Namen und den geheimen Schlüssel ein.",
    errorShort: "Der geheime Schlüssel scheint zu kurz zu sein.",
    errorSave: "Das Konto konnte nicht gespeichert werden.",
    selectedOneItem: "Ausgewählt",
    selectedMoreItems: "Ausgewählt",
    move: "Verschieben",
    moveAccounts: "Konten verschieben",
    folder: "Ordner",
    newFolder: "Neuer Ordner",
    createFolder: "Ordner erstellen",
    folderNameLabel: "Ordnername *",
    folderIconLabel: "Icon",
    folderColorLabel: "Farbe",
    principalFolder: "Kein Ordner",
    noFoldersCreated:
      "Sie haben keine Ordner erstellt. Bitte erstellen Sie zuerst einen.",
    emptyFolder: "Dieser Ordner ist leer.",
    errorMissingName: "Der Ordnername ist erforderlich.",
    pressToStart: "Tippen Sie auf +, um zu beginnen",
    settings: "Einstellungen",
    security: "Sicherheit",
    biometricBlockTitle: "Biometrische Authentifizierung",
    biometricBlockSubtitle: "FaceID / Fingerabdruck",
    keysManagement: "Schlüsselverwaltung",
    exportKeys: "Schlüssel exportieren",
    importKeys: "Schlüssel importieren",
    app: "App",
    privacyPolicy: "Datenschutzerklärung",
    about: "Über",
    appDescription:
      "Ein sicherer, privater und Open-Source 2FA-Authenticator. Ihre Schlüssel verlassen niemals Ihr Gerät.",
    seeGitHub: "Code auf GitHub ansehen",
    technologiesAndCredits: "Technologien & Credits",
    frameworkCore: "Framework-Code",
    ecosystem: "Ökosystem",
    navigation: "Navigation",
    iconography: "Ikonografie",
    secureStorage: "Sicherer Speicher",
    createdWithLove: "Mit Liebe für freie Software erstellt",
    gotIt: "Verstanden",
    unlockApp: `${APP_NAME} entsperren`,
    usePin: "PIN verwenden",
    verifyIdentity: "Bestätigen Sie Ihre Identität für den Zugriff.",
    verifyIdentityFallback: "Geben Sie Ihre PIN ein, um zuzugreifen.",
    unlock: "Entsperren",
    appBlocked: `${APP_NAME} ist gesperrt`,
    none: "Keine",
    folderNamePlace: "Bsp.: Arbeit, Privat...",
    selectDestination: "Ziel auswählen für",
    selectDestination2: "Konto/Konten",
  },
  it: {
    // Italian
    invalidCode: "Codice non valido",
    invalidCodeMsg:
      "Il codice QR scansionato non sembra essere un codice di autenticazione valido.",
    ok: "OK",
    grantPermission: "Concedi permesso",
    cameraAccessMsg:
      "Abbiamo bisogno di accedere alla fotocamera per scansionare il codice QR.",
    scanQR: "Scansiona QR",
    scanQR2: "Scansiona il codice QR",
    manualEntry: "Inserimento Manuale",
    unknownIssuer: "Sconosciuto",
    addAccount: "Aggiungi Account",
    cancel: "Annulla",
    myKeys: "Le mie chiavi",
    empty: "Nessun account ancora.",
    emptySub: "Tocca + per aggiungerne uno.",
    delete: "Elimina",
    deleteItems: "Eliminare elementi?",
    deleteAccounts: "Eliminare account?",
    deleteDefinitely: "Eliminare definitivamente",
    confirmDelete: "Stai per eliminare",
    confirmDelete2: "elemento/i",
    confirmDelete3:
      "\nSe elimini una cartella, verrà eliminato anche tutto il suo contenuto.\nQuesta azione non può essere annullata.",
    options: "Opzioni account",
    newAccount: "Nuovo Account",
    accNameLabel: "Nome account *",
    accNamePlace: "Es: La mia email personale",
    issuerLabel: "Fornitore (Opzionale)",
    issuerPlace: "Es: Google, Amazon...",
    secretLabel: "Chiave Segreta (Key) *",
    secretPlace: "JBSWY3DP...",
    iconLabel: "Icona",
    colorLabel: "Colore etichetta",
    save: "Salva Account",
    saving: "Salvataggio...",
    errorTitle: "Errore",
    errorMissing: "Inserisci almeno un nome e la chiave segreta.",
    errorShort: "La chiave segreta sembra troppo corta.",
    errorSave: "Impossibile salvare l'account.",
    selectedOneItem: "Selezionato",
    selectedMoreItems: "Selezionati",
    move: "Sposta",
    moveAccounts: "Sposta account",
    folder: "Cartella",
    newFolder: "Nuova Cartella",
    createFolder: "Crea Cartella",
    folderNameLabel: "Nome Cartella *",
    folderIconLabel: "Icona",
    folderColorLabel: "Colore",
    principalFolder: "Nessuna cartella",
    noFoldersCreated: "Non hai creato cartelle. Creane prima una.",
    emptyFolder: "Questa cartella è vuota.",
    errorMissingName: "Il nome della cartella è obbligatorio.",
    pressToStart: "Tocca + per iniziare",
    settings: "Impostazioni",
    security: "Sicurezza",
    biometricBlockTitle: "Autenticazione Biometrica",
    biometricBlockSubtitle: "FaceID / Impronta digitale",
    keysManagement: "Gestione chiavi",
    exportKeys: "Esporta chiavi",
    importKeys: "Importa chiavi",
    app: "App",
    privacyPolicy: "Informativa sulla Privacy",
    about: "Info",
    appDescription:
      "Un autenticatore a due fattori (2FA) sicuro, privato e open source. Le tue chiavi non lasciano mai il dispositivo.",
    seeGitHub: "Vedi codice su GitHub",
    technologiesAndCredits: "Tecnologie e Crediti",
    frameworkCore: "Codice Framework",
    ecosystem: "Ecosistema",
    navigation: "Navigazione",
    iconography: "Iconografia",
    secureStorage: "Archiviazione Sicura",
    createdWithLove: "Creato con amore per il Software Libero",
    gotIt: "Capito",
    unlockApp: `Sblocca ${APP_NAME}`,
    usePin: "Usa PIN",
    verifyIdentity: "Verifica la tua identità per accedere.",
    verifyIdentityFallback: "Inserisci il PIN per accedere.",
    unlock: "Sblocca",
    appBlocked: `${APP_NAME} è bloccata`,
    none: "Nessuna",
    folderNamePlace: "Es: Lavoro, Personale...",
    selectDestination: "Seleziona destinazione per",
    selectDestination2: "account",
  },
};

export const TEXTS = ALL_TEXTS[langCode || "en"];
