import * as Localization from "expo-localization";

const locale = Localization.getLocales()[0];
const langCode = locale ? locale.languageCode : "en";

const ALL_TEXTS: { [key: string]: { [key: string]: string } } = {
  en: {
    // English
    invalidCode: "Invalid code",
    invalidCodeMsg:
      "The scanned QR code does not appear to be a valid authentication code.",
    ok: "OK",
    grantPermission: "Grant Permission",
    cameraAccessMsg: "We need camera access to scan the QR code.",
    scanQR: "Scan QR",
    scanQR2: "Scan the QR code",
    manualEntry: "Manual Entry",
    unknownIssuer: "Unknown",
    addAccount: "Add Account",
    cancel: "Cancel",
    myKeys: "My keys",
    empty: "No accounts yet.",
    emptySub: "Tap + to add one.",
    delete: "Delete",
    deleteItems: "Delete items?",
    deleteAccounts: "Delete accounts?",
    deleteDefinitely: "Delete definitely",
    confirmDelete: "You are about to delete",
    confirmDelete2: "item(s)",
    confirmDelete3:
      "\nIf you delete a folder, everything inside will also be deleted.\nThis action cannot be undone.",
    options: "Account Options",
    newAccount: "New Account",
    accNameLabel: "Account Name *",
    accNamePlace: "Ex: My Personal Email",
    issuerLabel: "Provider (Optional)",
    issuerPlace: "Ex: Google, Amazon...",
    secretLabel: "Secret Key *",
    secretPlace: "JBSWY3DP...",
    iconLabel: "Icon",
    colorLabel: "Label Color",
    save: "Save Account",
    saving: "Saving...",
    errorTitle: "Error",
    errorMissing: "Please enter at least a name and a secret key.",
    errorShort: "Secret key seems too short.",
    errorSave: "Could not save account.",
    selected: "Selected",
    move: "Move",
    moveAccounts: "Move accounts",
    folder: "Folder",
    newFolder: "New Folder",
    createFolder: "Create Folder",
    folderNameLabel: "Folder Name *",
    folderIconLabel: "Icon",
    folderColorLabel: "Color",
    principalFolder: "No folder",
    noFoldersCreated: "You have no folders created. Please create one first.",
    emptyFolder: "This folder is empty.",
    errorMissingName: "Folder name is required.",
    pressToStart: "Tap + to get started",
  },
  es: {
    // Spanish
    invalidCode: "Código no válido",
    invalidCodeMsg:
      "El código QR escaneado no parece ser un código de autenticación válido.",
    ok: "OK",
    grantPermission: "Conceder Permiso",
    cameraAccessMsg: "Necesitamos acceso a la cámara para escanear el código QR.",
    scanQR: "Escanear QR",
    scanQR2: "Escanear el código QR",
    manualEntry: "Entrada Manual",
    unknownIssuer: "Desconocido",
    addAccount: "Añadir Cuenta",
    cancel: "Cancelar",
    myKeys: "Mis claves",
    empty: "No tienes cuentas aún.",
    emptySub: "Pulsa el + para añadir una.",
    delete: "Eliminar",
    deleteItems: "¿Eliminar elementos?",
    deleteAccounts: "¿Eliminar cuentas?",
    deleteDefinitely: "Eliminar definitivamente",
    confirmDelete: "Estás a punto de eliminar",
    confirmDelete2: "elemento(s)",
    confirmDelete3:
      "\nSi eliminas una carpeta, también se borrará lo que haya dentro.\nEsta acción no se puede deshacer.",
    options: "Opciones de cuenta",
    newAccount: "Nueva Cuenta",
    accNameLabel: "Nombre de la cuenta *",
    accNamePlace: "Ej: Mi Correo Personal",
    issuerLabel: "Proveedor (Opcional)",
    issuerPlace: "Ej: google, amazon...",
    secretLabel: "Clave Secreta (Key) *",
    iconLabel: "Icono",
    secretPlace: "JBSWY3DP...",
    colorLabel: "Color de etiqueta",
    save: "Guardar Cuenta",
    saving: "Guardando...",
    errorTitle: "Faltan datos",
    errorMissing: "Por favor, introduce al menos un nombre y la clave secreta.",
    errorShort: "La clave secreta parece demasiado corta.",
    errorSave: "No se pudo guardar la cuenta.",
    selected: "Seleccionado(s)",
    move: "Mover",
    moveAccounts: "Mover cuentas",
    folder: "Carpeta",
    newFolder: "Nueva Carpeta",
    createFolder: "Crear Carpeta",
    folderNameLabel: "Nombre de la Carpeta *",
    folderIconLabel: "Icono",
    folderColorLabel: "Color",
    principalFolder: "Sin carpeta",
    noFoldersCreated: "No tienes carpetas creadas. Crea una primero.",
    emptyFolder: "Esta carpeta está vacía.",
    errorMissingName: "El nombre de la carpeta es obligatorio.",
    pressToStart: "Pulsa + para empezar",
  },
  fr: {
    // French
    scanQR: "Scanner QR",
    manualEntry: "Saisie Manuelle",
    unknownIssuer: "Inconnu",
    addAccount: "Ajouter un compte",
    cancel: "Annuler",
    myKeys: "Mes Clés",
    empty: "Pas encore de comptes.",
    emptySub: "Appuyez sur + pour ajouter.",
    delete: "Supprimer",
    confirmDelete: "Que voulez-vous faire avec",
    options: "Options du compte",
    newAccount: "Nueva Cuenta",
    accNameLabel: "Nombre de la cuenta *",
    accNamePlace: "Ej: Mi Correo Personal",
    issuerLabel: "Proveedor (Opcional)",
    issuerPlace: "Ej: google, amazon...",
    secretLabel: "Clave Secreta (Key) *",
    secretPlace: "JBSWY3DP...",
    colorLabel: "Color de etiqueta",
    save: "Guardar Cuenta",
    saving: "Guardando...",
    errorTitle: "Faltan datos",
    errorMissing: "Por favor, introduce al menos un nombre y la clave secreta.",
    errorShort: "La clave secreta parece demasiado corta.",
    errorSave: "No se pudo guardar la cuenta.",
  },
  de: {
    // German
    scanQR: "QR scannen",
    manualEntry: "Manuelle Eingabe",
    unknownIssuer: "Unbekannt",
    addAccount: "Konto hinzufügen",
    cancel: "Abbrechen",
    myKeys: "Meine Schlüssel",
    empty: "Noch keine Konten.",
    emptySub: "Tippen Sie auf +, um eins hinzuzufügen.",
    delete: "Löschen",
    confirmDelete: "Was möchten Sie tun mit",
    options: "Kontooptionen",
    newAccount: "Nueva Cuenta",
    accNameLabel: "Nombre de la cuenta *",
    accNamePlace: "Ej: Mi Correo Personal",
    issuerLabel: "Proveedor (Opcional)",
    issuerPlace: "Ej: google, amazon...",
    secretLabel: "Clave Secreta (Key) *",
    secretPlace: "JBSWY3DP...",
    colorLabel: "Color de etiqueta",
    save: "Guardar Cuenta",
    saving: "Guardando...",
    errorTitle: "Faltan datos",
    errorMissing: "Por favor, introduce al menos un nombre y la clave secreta.",
    errorShort: "La clave secreta parece demasiado corta.",
    errorSave: "No se pudo guardar la cuenta.",
  },
  it: {
    // Italian
    scanQR: "Scansiona QR",
    manualEntry: "Inserimento Manuale",
    unknownIssuer: "Sconosciuto",
    addAccount: "Aggiungi Account",
    cancel: "Annulla",
    myKeys: "Le mie chiavi",
    empty: "Nessun account ancora.",
    emptySub: "Tocca + per aggiungerne uno.",
    delete: "Elimina",
    confirmDelete: "Cosa vuoi fare con",
    options: "Opzioni account",
    newAccount: "Nueva Cuenta",
    accNameLabel: "Nombre de la cuenta *",
    accNamePlace: "Ej: Mi Correo Personal",
    issuerLabel: "Proveedor (Opcional)",
    issuerPlace: "Ej: google, amazon...",
    secretLabel: "Clave Secreta (Key) *",
    secretPlace: "JBSWY3DP...",
    colorLabel: "Color de etiqueta",
    save: "Guardar Cuenta",
    saving: "Guardando...",
    errorTitle: "Faltan datos",
    errorMissing: "Por favor, introduce al menos un nombre y la clave secreta.",
    errorShort: "La clave secreta parece demasiado corta.",
    errorSave: "No se pudo guardar la cuenta.",
  },
};

export const TEXTS = ALL_TEXTS[langCode || "en"];
